on: [push]

jobs:
  update-sparql-endpoint-status:
    runs-on: ubuntu-latest
    name: Update SPARQL Endpoint Service Status
    steps:
    - uses: actions/checkout@v1
    - name: Download SPARQL Integrate
      run: wget -O si.jar https://github.com/SmartDataAnalytics/SparqlIntegrate/releases/download/sparql-integrate-bundle-1.0.2-SNAPSHOT/sparql-integrate-bundle-1.0.2-SNAPSHOT-jar-with-dependencies.jar
    - name: Run service check
      run: java -cp si.jar sparqlintegrate --w=trig/pretty sparql-endpoints-from-andre.ttl sparql-endpoints-from-andre-status.trig scripts/check-test.sparql > status.trig
    - name: Upload status
      uses: actions/upload-artifact@v1
      with:
        name: status
        path: status.trig
