---
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-sparql-endpoint-status:
    runs-on: ubuntu-latest
    name: Update SPARQL Endpoint Service Status
    steps:
    - uses: actions/checkout@v1
    - name: Download SPARQL Integrate
      run: wget -O si.jar https://github.com/SmartDataAnalytics/SparqlIntegrate/releases/download/sparql-integrate-bundle-1.0.2-SNAPSHOT/sparql-integrate-bundle-1.0.2-SNAPSHOT-jar-with-dependencies.jar
    - name: Run service check
      run: java -cp si.jar sparqlintegrate alive-endpoints-latest.ttl playground/endpoint-to-graph.sparql | java -cp si.jar ngs map -t '5000,5000' --sparql playground/check-test.sparql | java -cp si.jar sparqlintegrate --w=trig/pretty --u - 'CONSTRUCT WHERE { ?s ?p ?o }' > latest-status.ttl
    - name: Commit files
      run: |
        git add latest-status.trig
        git config --local user.email "cstadler@informatik.uni-leipzig.de"
        git config --local user.name "Claus Stadler"
        git commit -m "Adding latest status" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


#    - name: Upload status
#      uses: actions/upload-artifact@v1
#      with:
#        name: status
#        path: status.trig
